### ISSUE TITLE
Continous Integration Init

### ISSUE THREAD

**Issue by Ometeo** [Ometeo/Alfred#1]
Setup CI for building Backend & Frontend & running test.

- [x] Backend build with Travis CI
- [ ] Frontend build with Travis CI
- [x] Backend test run with Travis CI
- [ ] Frontend test run with Travis CI
